config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  resources :posts
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

    # 入力必須項目
    with_options presence: true do
        validates :title
        validates :start_date
        validates :end_date
    end

    # タイトル20文字、メモの長さ500文字を上限に設定
    validates :title,{length: {maximum: 20}}
    validates :memo,{length: {maximum: 500}}

    #バリデーションを定義 開始日より前の日付を登録できないように
    validate :start_end_check
    def start_end_check
        if start_date.present? && end_date.present? && start_date > end_date
        errors.add(:end_date, "は開始日より前の日付は登録できません。")
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(params.require(:post).permit(:title, :start_date, :end_date, :allday, :memo))
        if @post.save
            flash[:notice] = "投稿を保存しました"
            redirect_to posts_path #一覧へ
        else
            flash.now[:notice] = "投稿に失敗しました"
            render action: :new#新規投稿へ renderにすることで入力内容が消えないようにする
        end
    end

    def show
        @post = Post.find_by(id: params[:id])
    end

    def edit
        @post = Post.find_by(id: params[:id])
    end

    def update
        @post = Post.find_by(id: params[:id])
        if @post.update(params.require(:post).permit(:title, :start_date, :end_date, :allday, :memo))
            flash[:notice] = "IDが「#{@post.id}」の投稿を更新しました"
            redirect_to posts_path #一覧へ
        else
            flash[:notice] = "編集に失敗しました"
            redirect_to edit_post_path #編集画面へ
        end
    end

    def destroy
        @post = Post.find_by(id: params[:id])
        @post.destroy
        flash[:notice] = "IDが「#{@post.id}」の投稿を削除しました"
        redirect_to posts_path #一覧へ
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduleFile</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <h1>スケジュール管理アプリ</h1>
  </header>

  <body class="header_body">
    <!-- エラーメッセージ -->
    <%= yield %>  
  </body>


</html>

app/views/posts/edit.html.erb
<!-- 編集ページ -->
<h1 class="edit_head">予定を編集してください</h1>

<!-- 作成後情報を持っていなければcreateアクション、持っていればupdateアクションへ -->
<%= form_with model: @post do |f| %>
<!-- 背景 -->
    <div class="edit_flame">
        <div class="edit_title">
            <p class="edit_title_text"><%= f.label :title ,"タイトル" %></p>
            <p class="edit_title_form"><%= f.text_field :title %></p>
            <% if @post.errors.include?(:title) %>
            <p class="edit_error"><%= @post.errors.full_messages_for(:title).first %></p>
            <% end %>
        <!-- 開始日 -->
        <div class="edit_start">
            <p class="edit_start_text"><%= f.label :start_date ,"開始日" %></p>
            <p class="edit_start_form"><%= f.date_field :start_date %></p>
            <% if @post.errors.include?(:start_date) %>
            <p class="edit_error"><%= @post.errors.full_messages_for(:start_date).first %></p>
            <% end %>
        </div>
        <!-- 終了日 -->
        <div class="edit_end">
            <p class="edit_end_text"><%= f.label :end_date ,"終了日" %></p>
            <p class="edit_end_form"><%= f.date_field :end_date %></p>
            <% if @post.errors.include?(:end_date) %>
            <p class="edit_error"><%= @post.errors.full_messages_for(:end_date).first %></p>
            <% end %>
        </div>
    </div>
        <!-- 終日 -->
        <p class="edit_allday_form"><%= f.check_box :allday %> 終日の場合はチェックを入れます</p>

        <!-- メモ -->
        <p class="edit_memo_text"><%= f.label :memo ,"スケジュールメモ" %></p>
        <p class="edit_memo_form"><%= f.text_area :memo %></p>

        <!-- 送信 -->
        <%= link_to "キャンセル", posts_path, class:"btn edit_cancel" %></li>
        <%= f.submit " 保存 ", class:"edit_save" %>

</div>

<% end %>

<!-- フラッシュメッセージ -->
<div class="flash_message"><%= flash[:notice] %></div>

app/views/posts/index.html.erb
<!-- 投稿一覧ページ -->
<h1 class="index_head">予定一覧</h1>

<!-- 新規追加 posts/newへ飛ぶ -->
<%= link_to("＋ 新規追加", new_post_path, class: "new_post_btn") %>

<table class="index_table">
    <thead>
    <tr class="index_table_tr">
        <th class="index_table_th">ID</th>
        <th class="index_table_th">タイトル</th>
        <th class="index_table_th">開始日</th>
        <th class="index_table_th">終了日</th>
        <th class="index_table_th">終日</th>
        <th class="index_table_th">更新日</th>
        <th class="index_table_th">詳細</th>
        <th class="index_table_th">編集</th>
        <th class="index_table_th">削除</th>
    </tr>
    </thead>

    <tbody>
    <% @posts.each do |post| %>
    <tr>
        <td class="index_table_td"><%= post.id %></td>
        <td class="index_table_td"><%= post.title %></td>
        <td class="index_table_td"><%= l post.start_date, format: :short %></td>
        <td class="index_table_td"><%= l post.end_date, format: :short %></td>
        <td class="index_table_td"><%= post.allday ? "○":" " %></td>
        <td class="index_table_td"><%= l post.updated_at, format: :long %></td>
        <td class="index_table_td"><%= link_to "詳細", post_path(post) %></td><!-- posts/showへ飛ぶ -->
        <td class="index_table_td"><%= link_to "編集", edit_post_path(post) %></td> <!-- posts/editへ飛ぶ -->
        <td class="index_table_td"><%= link_to "削除", post_path(post), data: { method: :delete,confirm: "予定を削除しますか？"} %></td>
    </tr>
    <% end %>
    </tbody>
</table> 

<!-- フッター -->
<footer class="index_footer">
    <p class="index_total">予定合計 <span class="index_total_span"><%= Post.count %></span>件</p>

    <div class="today_view">
    本日の日付 <%= l Time.now, format: :short %>
    </div>
</footer>

<!-- フラッシュメッセージ -->
<div class="flash_message"><%= flash[:notice] %></div>

app/views/posts/new.html.erb
<!-- 新規登録ページ -->
<h1 class="new_head">予定の新規追加</h1>

<!-- フォーム一覧 -->
<%= form_with model: @post do |f| %>
    <!-- フォーム全体 -->
    <div class="new_flame">

        <!-- タイトル入力フォーム -->
        <p class="new_title_text"><%= f.label :title ,"タイトル" %></p>
        <p class="new_title_form"><%= f.text_field :title %></p>
        <!-- エラーメッセージ -->
        <% if @post.errors.include?(:title) %>
            <p class="new_error"><%= @post.errors.full_messages_for(:title).first %></p>
        <% end %>

    <!-- 開始日入力フォーム -->
    <div class="new_start">
        <p class="new_start_text"><%= f.label :start_date ,"開始日" %></p>
        <p class="new_start_form"><%= f.date_field :start_date %></p> <!--カレンダー入力 -->
        <!--エラーメッセージ -->
        <% if @post.errors.include?(:start_date) %>
            <p class="new_error"><%= @post.errors.full_messages_for(:start_date).first %></p>
        <% end %>
    </div>

    <!-- 終了日入力フォーム -->
    <div class="new_end">
        <p class="new_end_text"><%= f.label :end_date ,"終了日" %></p>
    <p class="new_end_form"><%= f.date_field :end_date %></p> <!--カレンダー入力 -->
    <!-- エラーメッセージ -->
        <% if @post.errors.include?(:end_date) %>
            <p class="new_error"><%= @post.errors.full_messages_for(:end_date).first %></p>
        <% end %>
    </div>

    <!-- 終日選択フォーム -->
    <p class="new_allday_form"><%= f.check_box :allday %> 終日の場合はチェックを入れます</p>

    <!-- メモ入力フォーム -->
    <p class="new_memo_text"><%= f.label :memo ,"スケジュールメモ" %></p>
    <p class="new_memo_form"><%= f.text_area :memo %></p>

    <!-- 一覧画面に飛ぶ -->
    <%= link_to "キャンセル", posts_path, class:"btn new_cancel" %></li>
    <!-- 送信フォーム -->
    <%= f.submit " 保存 ", class:"new_save" %>

    </div>
<% end %>

<!-- フラッシュメッセージ -->
<div class="flash_message"><%= flash[:notice] %></div>

app/views/posts/show.html.erb
<!-- 詳細ページ -->

<!-- 一覧に飛ぶ -->
<p class="show_index"><%= link_to "← 一覧に戻る", posts_path, class: "show_index_text" %></p>

<!-- タイトル名 -->
<p class="show_title_name"><%= @post.title %></p>

<!-- 編集ボタン -->
<li class="show_edit">
        <%= link_to edit_post_path do%> <!-- users/editへ飛ぶ -->
        <%= image_tag "icon_pencil.png", class:"icon_pencil"%><p class="show_edit_text">編集</p>
        <% end %>
</li>
<!-- 背景 -->
<div class="show_table_flame">
    <!-- 表 -->
    <table class="show_table">
        <tr class="show_table_tr">
            <th class="show_table_th">開始日</th>
            <td class="show_table_td"><%= l @post.start_date, format: :short %></td>
        </tr>
        <tr class="show_table_tr">
            <th class="show_table_th">終了日</th>
            <td class="show_table_td"><%= l @post.end_date, format: :short %></td>
        </tr>
        <tr class="show_table_tr">
            <th class="show_table_th">終日</th>
            <td class="show_table_td"><%= @post.allday ? "○":" "  %></td> <!-- 入力されているなら○、されていないなら空白 -->
        </tr>
        <tr class="show_table_tr">
            <th class="show_table_th">スケジュールメモ</th>
            <td class="show_table_td"><%= @post.memo %></td>
        </tr>
    </table>
</div>